version: '3.3'
services:
  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'employees'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3318:3306
    expose:
      - '3318:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
  